/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh0: THREE.Mesh
    Mesh0_1: THREE.Mesh
    Mesh0_2: THREE.Mesh
  }
  materials: {
    ['20202020']: THREE.MeshStandardMaterial
    m1: THREE.MeshStandardMaterial
    m2: THREE.MeshStandardMaterial
  }
}

type ContextType = any

const context = createContext<ContextType>(null)
export function Instances({ children, ...props }: { children: React.ReactNode; [key: string]: any }) {
  const { nodes } = useGLTF('/Kandang.gltf') as unknown as GLTFResult
  const instances = useMemo(
    () => ({
      Mesh: nodes.Mesh0,
      Mesh1: nodes.Mesh0_1,
      Mesh2: nodes.Mesh0_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Kandang(props: React.ComponentProps<'group'>) {
  const instances = useContext(context) as any
  const groupRef = useRef<THREE.Group>(null)
  
  // Animation loop
  useFrame((state) => {
    if (groupRef.current) {
      // Gentle floating animation
      groupRef.current.position.y = Math.sin(state.clock.elapsedTime * 0.5) * 0.05
      
      // Subtle rotation animation
      groupRef.current.rotation.y = Math.sin(state.clock.elapsedTime * 0.3) * 0.05
    }
  })
  
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group name="Scene">
        <group name="Node0" userData={{ name: 'Node0' }}>
          <group name="Node1" userData={{ name: 'Node1' }}>
            <instances.Mesh name="Mesh0">
              <meshStandardMaterial 
                color="#B8860B" 
                metalness={0.3} 
                roughness={0.7}
                emissive="#3a2f0b"
                emissiveIntensity={0.1}
              />
            </instances.Mesh>
            <instances.Mesh1 name="Mesh0_1">
              <meshStandardMaterial 
                color="#DC143C" 
                metalness={0.4} 
                roughness={0.5}
                emissive="#4a0a10"
                emissiveIntensity={0.15}
              />
            </instances.Mesh1>
            <instances.Mesh2 name="Mesh0_2">
              <meshStandardMaterial 
                color="#4682B4" 
                metalness={0.2} 
                roughness={0.6}
                emissive="#0f1f2e"
                emissiveIntensity={0.12}
              />
            </instances.Mesh2>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Kandang.gltf')
